name: VoteHandler
version: 1.2
main: com.thepastimers.VoteHandler.VoteHandler
softdepend: [Database,Permission,Rank,Votifier]
commands:
    testvote:
        description: Admin command for testing Votifier
    vote:
        description: main vote command