name: VoteHandler
version: 1.4
main: com.thepastimers.VoteHandler.VoteHandler
softdepend: [Database,Permission,Rank,Votifier,Chat]
commands:
    testvote:
        description: Admin command for testing Votifier
    vote:
        description: main vote command