name: ChestProtect
version: 1.2
main: com.thepastimers.ChestProtect.ChestProtect
softdepend: [Database,Permission,Coord,Plot]
commands:
    protect:
        description: Chest protection command