name: ChestProtect
version: 1.9
main: com.thepastimers.ChestProtect.ChestProtect
softdepend: [Database,Permission,Coord,Plot,Worlds]
commands:
    protect:
        description: Chest protection command