name: AdminTools
version: 1.3
main: com.thepastimers.AdminTools.AdminTools
softdepend: [Database,Permission,Logger,Coord]
commands:
    ban:
        description: bans user
    kick:
        description: kicks user
    pardon:
        description: pardon user
    entities:
        description: entities command
    ping:
        description: get player ping
    spawner:
        description: gives spawner