name: AdminTools
version: 1.0
main: com.thepastimers.AdminTools.AdminTools
softdepend: [Database,Permission]
commands:
    ban:
        description: bans user
    kick:
        description: kicks user
    pardon:
        description: pardon user
    entities:
        description: entities command