name: Home
version: "1.7"
api-version: "1.15"
main: com.thepastimers.Home.Home
depend: [Database, Permission]
softdepend: [Rank,UserMap]
commands:
    home:
        description: home command
    delhome:
        description: delete home
    sethome:
        description: set home
    listhome:
        description: list homes
    maxhome:
        description: set max homes
    groupmaxhome:
        description: set group max homes
    forcehome:
        description: Force teleport to a home