name: Home
version: 1.5
main: com.thepastimers.Home.Home
softdepend: [Database,Permission,Rank,CombatLog,Worlds]
commands:
    home:
        description: home command
    delhome:
        description: delete home
    sethome:
        description: set home
    listhome:
        description: list homes
    maxhome:
        description: set max homes
    groupmaxhome:
        description: set group max homes
    forcehome:
        description: Force teleport to a home