name: Chat
version: 2.1
main: com.thepastimers.Chat.Chat
depend: [BukkitBridge, Database]
commands:
    codes:
        description: lists allowed chat codes
    testChat:
        description: blah