name: Chat
version: 2.1
main: com.thepastimers.Chat.Chat
softdepend: [Database,Logger,Alias,Worlds]
commands:
    codes:
        description: lists allowed chat codes
    menu:
        description: shows a menu
    testChat:
        description: blah