name: Chat
version: 1.8
main: com.thepastimers.Chat.Chat
softdepend: [Database,Logger]
commands:
    codes:
        description: lists allowed chat codes
    menu:
        description: shows a menu