name: Chat
version: 1.7
main: com.thepastimers.Chat.Chat
softdepend: [Database,Worlds,Logger]
commands:
    codes:
        description: lists allowed chat codes
    menu:
        description: shows a menu