name: TradeSign
version: 1.0
main: com.thepastimers.TradeSign.TradeSign
softdepend: [Database,Money,Rank,Permission,ItemName,Coord,Worlds,UserMap]
commands:
    sign:
        description: sign commands