name: CastleWars
version: 0.5
main: com.thepastimers.CastleWars.CastleWars
softdepend: [Database,Plot,Permission,Money,Coord,Pattern,Chat,Worlds]
commands:
    cw:
        description: castle wars main command