name: CastleWars
version: 0.3
main: com.thepastimers.CastleWars.CastleWars
softdepend: [Database,Plot,Permission,Money,Coord,Pattern,Chat]
commands:
    cw:
        description: castle wars main command