name: CastleWars
version: 0.8
main: com.thepastimers.CastleWars.CastleWars
softdepend: [Database,Plot,Permission,Money,Coord,Pattern,Chat,Worlds]
commands:
    cw:
        description: castle wars main command
    reloadCastles:
        description: reloads castle cache