name: CastleWars
version: 0.1
main: com.thepastimers.CastleWars.CastleWars
softdepend: [Database,Plot,Permission,Money,Coord,Pattern]
commands:
    cw:
        description: castle wars main command