name: Plot
version: 4.5
main: com.thepastimers.Plot.Plot
softdepend: [Database,Permission,Money]
commands:
    plot:
        description: plot commands
    subplot:
        description: subplot commands
    reloadplots:
        description: reloads plot data from database