name: Plot
version: 4.8
main: com.thepastimers.Plot.Plot
softdepend: [Database,Permission,Coord,Money,Worlds,Logger]
commands:
    plot:
        description: plot commands
    subplot:
        description: subplot commands
    reloadplots:
        description: reloads plot data from database