name: Plot
version: "4.8"
api-version: "1.15"
main: com.thepastimers.Plot.Plot
softdepend: [Database,Permission,Coord]
commands:
    plot:
        description: plot commands
    subplot:
        description: subplot commands
    reloadplots:
        description: reloads plot data from database