name: Permission
version: 1.6
main: com.thepastimers.Permission.Permission
softdepend: [Database,Rank,UserMap]
commands:
    perms:
        description: give/remove/check perms
    groupperms:
        description: give/remove/check group perms
