name: Permission
version: 1.5
main: com.thepastimers.Permission.Permission
softdepend: [Database,Rank]
commands:
    perms:
        description: give/remove/check perms
    groupperms:
        description: give/remove/check group perms
