name: Warp
version: 0.4
main: com.thepastimers.Warp.Warp
softdepend: [Database,Permission,CombatLog,Worlds]
commands:
    warp:
        description: warp command
    setwarp:
        description: set warps
    delwarp:
        description: remove warps