name: Warp
version: 0.2
main: com.thepastimers.Warp.Warp
softdepend: [Database,Permission,CombatLog]
commands:
    warp:
        description: warp command
    setwarp:
        description: set warps