name: ExtCommands
version: 1.3
main: com.thepastimers.ExtCommands.ExtCommands
softdepend: [Permission, Metrics,Rank,Worlds,ItemName]
commands:
    spawn:
        description: teleports to spawn
    setspawn:
        description: sets spawn point
    tpe:
        description: teleports to coordinates
    clear:
        description: removes certain things
    itemCheck:
        description: gives info about held item
    opCheck:
        description: checks if player has op
    pot:
        description: Kurama_09's command
    setTitle:
        description: set own title (if permissions)
    hide:
        description: Vanish player
    spawnDragon:
        description: Spawns Ender Dragon
    stack:
        description: stacks items