name: ItemName
version: 1.5
api-version: "1.15"
main: com.thepastimers.ItemName.ItemName
softdepend: [Permission]
commands:
    nameitem:
        description: Names item in hand
    listitems:
        description: Lists all items in the game