name: Magic
version: 1.3
main: com.thepastimers.Magic.Magic
softdepend: [Database,Permission,ItemName,Worlds]
commands:
    cast:
        description: cast spell
    checkmana:
        description: check mana