name: Spawner
version: 0.4
main: com.thepastimers.Spawner.Spawner
softdepend: [Database,Permission,Worlds]
commands:
    createspawn:
        description: creates a spawn point
    runspawn:
        description: activates a group of spawn points
    listspawns:
        description: lists spawn points