name: Rank
version: "1.6"
api-version: "1.15"
main: com.thepastimers.Rank.Rank
depend: [Database,UserMap]
commands:
    rank:
        description: rank command
    title:
        description: title command