name: Rank
version: 1.5
main: com.thepastimers.Rank.Rank
depends: [Database]
softdepend: [Chat,UserMap]
commands:
    rank:
        description: rank command
    title:
        description: title command