name: Rank
version: 1.5
main: com.thepastimers.Rank.Rank
softdepend: [Database,Chat,UserMap]
commands:
    rank:
        description: rank command
    title:
        description: title command