name: Worlds
version: 1.7
main: com.thepastimers.Worlds.Worlds
softdepend: [Database,CombatLog,inventory,UserMap]
commands:
    go:
        description: sends players to world
    world:
        description: allows changing of world parameters