name: Teleport
version: 0.4
main: com.thepastimers.Teleport.Teleport
softdepend: [Rank,Permission,Mute,CombatLog]
commands:
    tp:
        description: teleport command
    tpa:
        description: teleport to others
    tpaccept:
        description: accept a teleport request
    tpdeny:
        description: deny a teleport request